export const Map = '#layoutSearchLocation';
export const TableCell = '[role="gridcell"]';
export const TableRow = '[role="row"]';
export const GridLoader = '.k-loading-mask';
export const PageLoader = '.lock-off';
export const DropdownOption = '[role="option"]';
export const Tab = '[role="tab"]';
export const MapLoader = '.area-locked';
export const FromDate = '#fromDate';
export const ToDate = '#toDate';
export const GoButton = '#go';
export const Checkbox = '[type="checkbox"]';
export const MapSelector = '#compareDiv';
export const MapLocationFilter = '#locationFilter';
export const MapLocationFilterArrow = '.k-top.k-bot > .k-icon';
export const MapLocationFilterOption = '.k-in';
export const GlobalFilterSecondLvl = '.by > .fields > .pop-down > .pop';
export const CommodityFilterList = '#divCommodity_ListViewDiv';
export const SelectButton = '#btnSelect';
export const SaveButton = '.k-grid-update';
export const EditButton = '[title="Edit"]';
export const VisibleDatePicker = '.dp_visible';
export const PreviousButtonDatePicker = '.dp_previous';
